### ISSUE TITLE
Dead clients are not removed

### ISSUE THREAD

**Issue by Chilinot** [TheGrandmother/MUD#17]
When a socket is closed the connection is not removed serverside!

**Comment by Chilinot** [comment]
This is causing a memory leak that tanks the server.

**Comment by TheGrandmother** [comment]
Is it that the actual connection doesn't or just that the memory from the thread isn't freed.

I dont think threads are garbage collected when they are done. They need to be explicitly terminated.

**Comment by Chilinot** [comment]
Since all clients are stored in an extra Map[1] that keeps track of legit MUD connections we need to make sure they are removed from that list when their connection is terminated. Right now they are not removed from that list, which means that there is still a reference to their WebSocket connection so the garbage collector won't remove their object.

[1]https://github.com/TheGrandmother/MUD/blob/master/src/main/java/ioopm/mud/communication/websocket/WSServerAdapter.java#L33
