### ISSUE TITLE
Connections never timeout

### ISSUE THREAD

**Issue by TheGrandmother** [TheGrandmother/MUD#21]
Clients never gets removed or timedout. I logged in a bunch of users like 30 minutes ago and they are still active :/

**Comment by Chilinot** [comment]
If you dont close their connection to their server they will not timeout.

**Comment by Chilinot** [comment]
How was the test performed?

**Comment by Chilinot** [comment]
I added a statement to the server that manually closes the connection when a LOGOUT message is received.

**Comment by TheGrandmother** [comment]
I just logged in with a bunch of different users rough the browser interface to test the say action.

What I did was I just reloaded the page to log in a new user which should have terminated the previous connection.

**Comment by Chilinot** [comment]
Are you sure the server was running the latest version at the time with the memory leak and logout fix?

**Comment by TheGrandmother** [comment]
The client does not send a logout when it is closed. Shouldn't the heart beats automatically close the connection after a timeout

**Comment by Chilinot** [comment]
There are no heartbeats any more.

**Comment by TheGrandmother** [comment]
Yes I was using the latest version.

**Comment by TheGrandmother** [comment]
Why has the heart stopped beating?

The server would have to automatically send the logout message to the game engine. It can't be done reliably on the browser side.

**Comment by Chilinot** [comment]
Then i need to look into how the websocket library handles disconnects and whether or not it timesout the connection. It might be that it considers your page reload to be the same connection and never terminate it.

**Comment by TheGrandmother** [comment]
I think there is a keep alive option for websocket connections which might fuck up

**Comment by Chilinot** [comment]
Looking at the source of the library, it seems to close the connection when it finds EOT (possibly end of transmission, there are no comments or documentation to explain it) or when it receives an closing handshake from the other side.

**Comment by TheGrandmother** [comment]
Then we need to re implement heart beats.
It's impossible to send a logout message if the browser shuts down unexpectedly.

**Comment by TheGrandmother** [comment]
Solved by 05c1d74e955124912a8d092b267add0ac26c3abb
