### ISSUE TITLE
Re-add heartbeats!

### ISSUE THREAD

**Issue by Chilinot** [TheGrandmother/MUD#26]
We need to re add hearbeats to the game to detect all disconnects. Currently the game wont detect when a player refreshes the webpage or simply closes the browser/tab. This can be fixed by re-introducing heartbeats to the MUD.

**Comment by TheGrandmother** [comment]
I'll look into the possibility of having the interface maintain the connection when a refresh happens.

**Comment by Chilinot** [comment]
Heartbeats seem to be working in the server and the old client again. The commits can be found in the heartbeat branch :)

**Comment by TheGrandmother** [comment]
How does the heartbeat exchange look ?

**Comment by Chilinot** [comment]
Client sends heartbeats every 5 seconds. The server immediately responds to these messages.

If the server detects that a client has not sent _any_ messages within at least 5*heartbeat-frequency (25 seconds) it assumes the connection is dead and kills it.

**Comment by TheGrandmother** [comment]
How does the heartbeat messages look ?

I propose we add a new rule that we must specify every new message thingy on the wiki as soon as we push them.

**Comment by Chilinot** [comment]
The heartbeats are the exact same messages that was used earlier. I just made the server and client send them again.

Structure:
sender;receiver;HEARTBEAT;null;timestamp;

sender;receiver;HEARTBEAT_REPLY;null;timestamp;

**Comment by TheGrandmother** [comment]
Fixed! 7fca376eba7646337b1b5d633ea3614f85b312e3
