### ISSUE TITLE
Old client does not timeout server

### ISSUE THREAD

**Issue by Chilinot** [TheGrandmother/MUD#29]
I forgot to add a timeout in clients. Currently the old clients does not terminate the connection if the server does not respond to their messages.

**Comment by Chilinot** [comment]
Considering this only affects the old client, this is a very very very low prio issue.

**Comment by TheGrandmother** [comment]
I consider the old client to be completely archaic.
I think we should actually drop it completely from the project once the web interface is stable.

**Comment by Chilinot** [comment]
Closed due to #30
