### ISSUE TITLE
Server sends multiple responses to failed registration.

### ISSUE THREAD

**Issue by TheGrandmother** [TheGrandmother/MUD#31]
Server sends both a `GENERAL_ERROR` and a `REGISTRATION_REPLY` on a failed registration attempt.

I think its best if it only sends a registration reply.

**Comment by Chilinot** [comment]
What would cause a registration to fail?
Den 14 dec 2015 2:14 em skrev "Henrik Sommerland" <notifications@github.com

**Comment by TheGrandmother** [comment]
if the username is already taken
