### ISSUE TITLE
Move issues, wiki, etc to taiga.io instead

### ISSUE THREAD

**Issue by Chilinot** [TheGrandmother/MUD#38]
I have recently discovered taiga.io and it is really cool! Basically it supports both kanban and scrum, as well as having a really nice issue tracker and more goodies.

The best part of it is that it is completely compatible with both gitlab and github with webhooks!

More on it:
https://taiga.io/support/github-integration/
https://taiga.io/support/changing-elements-status-via-commit-message/

**Comment by Chilinot** [comment]
But we are probably gonna loose the awesome code review stuffs that github has :(

**Comment by TheGrandmother** [comment]
https://waffle.io/
This is also nice.
It a appears to be a bit more "light" than taiga

**Comment by TheGrandmother** [comment]
https://waffle.io/thegrandmother/MUD
Okay it was quite easy to set up :P

**Comment by Chilinot** [comment]
Nice, that seems pretty sweet as well :)
Den 21 apr 2016 7:45 em skrev "Henrik Sommerland" <notifications@github.com

**Comment by TheGrandmother** [comment]
And i wrote this comment from waffle :p

**Comment by TheGrandmother** [comment]
The github events doesn't get pushed to taiga. It works for waffle but not for taiga :/

**Comment by Chilinot** [comment]
Did you fix the webhooks for taiga?

**Comment by Chilinot** [comment]
I really like the waffle solution as it doesnt remove anything from github, it just adds functionality to what we already have :)

**Comment by TheGrandmother** [comment]
Agreed!

**Comment by TheGrandmother** [comment]
I think Encore uses it as well

**Comment by TheGrandmother** [comment]
I'm closing this, since we are rolling with waffles:)
