### ISSUE TITLE
Modal input in client does not work in firefox

### ISSUE THREAD

**Issue by Chilinot** [TheGrandmother/MUD#49]
Currently it is not possible to use the web-based client due to the new modal input when using it through firefox. The input field does not accept the input it is given. I.e. pressing enter does nothing.

**Comment by TheGrandmother** [comment]
Yes it does.  #48 fixes it.
Or at least for me.

**Comment by Chilinot** [comment]
It does not work for me.

**Comment by TheGrandmother** [comment]
Strange. I'm on firefox now and it works?

**Comment by Chilinot** [comment]
What version are you using? I'm on 45, and it does not respond for me.

**Comment by TheGrandmother** [comment]
press `ctrl+shft+c` and tell me what error you get.

**Comment by Chilinot** [comment]
![2016-04-28-094546_1916x1041_scrot](https://cloud.githubusercontent.com/assets/1773227/14878805/2706b6ba-0d26-11e6-9885-182ae7c606fa.png)

**Comment by TheGrandmother** [comment]
Okay..... That is seriously bad. 
It appears like you are not even connected and it doesn't find anything in the other file. It might be that your version of firefox handles scoping differently.

What version are you using ?

**Comment by TheGrandmother** [comment]
Okay... apparently it doesn't allow the connection at:
[`socket = new WebSocket("ws://46.101.109.56:1337");`](https://github.com/TheGrandmother/MUD/blob/gh-pages/frontend/communication.js#L11)

Which is seriously lame.

Are you using strange security settings.

**Comment by Chilinot** [comment]
I found the issue... I forgot that my firefox settings block all non-encrypted communication while connected over https. And i automatically connect to https if it is available. So my browser could not connect to the server because we havent implemented SSL yet.

**Comment by TheGrandmother** [comment]
Awesome.
Does it work if you disable that.

**Comment by Chilinot** [comment]
Yep

**Comment by TheGrandmother** [comment]
Coool.
